### ISSUE TITLE
Rename default branch to main

### ISSUE THREAD

**Issue by BenjaminMichaelis** [IntelliTect/PSToolbox#85]
Specific instructions can be viewed here: https://github.com/github/renaming#rename-existing

- [ ] Code owner needs to rename default branch from master to main
- [ ] Check and update and correlated actions that refer to branch 'master'
- [ ] If you have a fork and/or local clone, here are the steps you need to take:
  - Navigate to your fork on GitHub, go to the Settings tab, then the Branches tab, and then under Default branch, click the pencil icon to rename the default branch to main.

- [ ] If you have a local clone, run the following commands in Git Bash:
```
git branch -m master main
git fetch origin
git branch -u origin/main main
```

**Comment by worseTyler** [comment]
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a

Running this should also set up your local version of the repo
